# ==========================================================
# APPLICATION
# ==========================================================
spring.application.name=lifelink-backend

# ==========================================================
# SERVER
# ==========================================================
server.port=8080

# ==========================================================
# MONGODB
# ==========================================================
spring.data.mongodb.uri=mongodb://localhost:27017/lifelink_db

# Automatically create indexes from @Indexed annotations
spring.data.mongodb.auto-index-creation=true

# ==========================================================
# LOGGING
# ==========================================================
logging.level.org.springframework.security=INFO
logging.level.org.springframework.data.mongodb=INFO

# ==========================================================
# JACKSON
# ==========================================================
spring.jackson.default-property-inclusion=non_null

# ==========================================================
# FILE UPLOAD
# ==========================================================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ==========================================================
# PROFILE
# ==========================================================
spring.profiles.active=dev